### ISSUE TITLE
second click doesn't make format undo

### ISSUE THREAD

**Issue by kai452** [tessus/joplin-plugin-menu-shortcut-toolbar#2]
like the Joplin-Default Icons eg strikethrough, mark, bold,..
these icons won't undo / toggle their formating

**Comment by tessus** [comment]
Can't reproduce.

![Aug-14-2021 20-23-59](https://user-images.githubusercontent.com/223439/129463289-36bea7c2-cfd3-460a-8db6-2f081cad6435.gif)

**Comment by tessus** [comment]
What about this issue? Did you see my screen cast?

**Comment by kai452** [comment]
Hi,
sorry, got no hint, that there was a new comment of You.
Ok, that works as usual.

But I'am using the RichTextEditor. Inbuild commands, e.g. bold, will do bold writing without showing the wrappings (++).
Therefore I can mark the whole word with one click and undo the former command.
Thats different when using Your commands: the wrappings will be shown. Therefore I is unpossible to mark the word with just a click, instead You have mark it explicite with the mouse.

By the way, my command line looks different:
![image](https://user-images.githubusercontent.com/53316526/129666347-62442032-f1cf-4c11-8d76-5fc941b2cbb8.png)

**Comment by tessus** [comment]
Right, the way the plugin is coded makes it impossible to automatically select the new text after the old one is replaced.

I have never used the rich text editor and thus also not tested my plugin with it. I am not sure why your toolbar looks different. There are a bunch of options in the configuration of the plugin....

<img width="649" alt="image" src="https://user-images.githubusercontent.com/223439/129702032-96aa1a90-e42c-4cbf-81c5-6aef8db6aba4.png">
