### ISSUE TITLE
How to install your plugin?

### ISSUE THREAD

**Issue by NordNordOst** [tessus/joplin-plugin-menu-shortcut-toolbar#4]
Hi tessus, hi everyone, 

I really would like to use underlining in my Joplin-notes. 

On my search for a solution I found this hint on the web to your / this plugin ([https://discourse.joplinapp.org/t/menu-items-shortcuts-toolbar-icons/17372](url)). 

Because I'm just a user and this is just my 2nd visit on GitHub I have to admit not having a clue on how to install your / this plugin. 

Unfortunately, 

- I neither could find your / this plugin in the official _Joplin Plugin Repository_ ([https://github.com/joplin/plugins/blob/master/README.md#plugins](url)) 
- nor did I found a chapter called _Installation_ in your / the Code-section like e. g. for the plugin _ABC Sheet Music_ ([https://github.com/joplin/plugin-abc-sheet-music](url)).  

As I said I'm a newbie and therefor I would appreciate any helpful hints on how to install your / this plugin in Joplin.  

Many thanks in advance. 

Best wishes, NordNordOst

**Comment by tessus** [comment]
abc sheet music is not my plugin. Btw, this would be much better to discuss on the forum....

Anyway, here is what you have to do:

- Open Joplin settings (On macOS `cmd+,`, on linux/win `Tools > Options`
- go to Markdown and check `Enable ++insert++ syntax`
- go to Plugins and type `menu` into the search field
    <img width="633" alt="image" src="https://user-images.githubusercontent.com/223439/149835242-dfa45bac-3493-43c0-a718-7b97f3951dc4.png">
- click on install
- restart Joplin

**Comment by NordNordOst** [comment]
Hi tessus, 

first of all I like to thank you very much for your help regarding the installation of your plugin _“Menu items, Shortcuts, Toolbar icons”_. 

I followed your instructions to install your plugin. Everything worked flawlessly. Immediately afterwards I used the underlining feature of your plugin in my text. And that worked flawlessly too. I really am pretty happy about that.  \o/  That helps me a lot. 

With the reference to the plugin _"ABC Sheet Music"_ I just wanted to show that there I found an installation guide directly in the code-section of the page. 

I apologize for any inconvenience. I would much appreciate if you could answer one last question: Which forum do you mean with the hint? 
 

> “Btw, this would be much better to discuss on the forum.…“

Is there a forum for such questions here on GitHub or do you mean the Joplin forum [https://discourse.joplinapp.org/](url)? - Many thanks in advance for your effort.  

Have a nice day and many greetings to Canada  

newbie NordNordOst

**Comment by tessus** [comment]
Yep, I meant https://discourse.joplinapp.org/ 
We use github only for reproducible bugs and accepted feature requests.

Btw, you can even use `Login with github` on the forum.

> Have a nice day and many greetings to Canada

Thanks! Have a nice day/evening/night/morning as well.

**Comment by NordNordOst** [comment]
Hi tessus, 

thank you very much for your hints. 

I just created my account on the Joplin forum accordingly and will put my questions there. 

I got it. I only will put 
> reproducible bugs and accepted feature requests 

here on GitHub in the future. 

I wonder why on GitHub not one of my aforementioned weblinks in my texts to you above work but your weblink works just fine!? Is there a special treatment other than to use "Add a link" and put the weblink into the square brackets I have to follow? - Any hint is much appreciated. Many thanks in advance.  

Best wishes 

NordNordOst

**Comment by tessus** [comment]
Github also uses markdown. Links in markdown can be written in 3 different ways:

```
[text here](link)
```

```
<link>
```

```
[text here][id]

[id]: link
```

Some markdown parsers automatically recognize links (or use the linkify option) and make them clickable, thus just pasting a link without the `<>` brackets will work in many cases too.

**Comment by NordNordOst** [comment]
Hi tessus, 

thanks for the tips regarding using weblinks here on GitHub; very kind of you. 

Next I'll try your three examples to put a weblink in Markdown here on GitHub: 

1.  Your first possibility to create  a weblink with a title I can find in the paragraph _Links_ within the chapter [Basic Syntax](https://www.markdownguide.org/basic-syntax/) in the _Markdown Guide_. 
2. Your second possibility to just put a weblink without a title into the text is explained in the aforementioned chapter within the paragraph _URLs and Email Addresses_ (See: <https://www.markdownguide.org/basic-syntax/>). 
3. The third possibility to use an URL without any brackets in the source text is explained in the paragraph _Automatic URL Linking_ in the _Markdown Guide_. One can find it there in the chapter called _Extended Syntax_: https://www.markdownguide.org/extended-syntax/ (8-> Last but not least, I have to admit, that I do not yet understand the role of the _[id]:_ in your third example.) 

While writing and using the preview-function here on GitHub it works well. _But what I'm already wondering very excitedly is, if it still works after sending this comment!?_  

3, 2, 1, Test. -> Moment of Truth. 

Tessus, I wish you a nice week-end. 

Greetings 

NordNordOst

**Comment by NordNordOst** [comment]
It works! <- I'm happy.   \o/

**Comment by tessus** [comment]
Reference style links are useful when you want to have a list of links at the bottom of the note, but still use them in the note, especially when you want to use the same link more than just once.

Here's an example:

```
This my [wiki][wiki] and has a few interesting articles. Just check them out [here][wiki]. But of course there are many more links that can be part of the note, like for instance the link on the Joplin's [website][joplin] that explains how to use [markdown][md].

[wiki]: https://evermeet.cx/wiki
[joplin]: https://joplinapp.org/
[md]: https://joplinapp.org/markdown/
```

This my [wiki][wiki] and has a few interesting articles. Just check them out [here][wiki]. But of course there are many more links that can be part of the note, like for instance the link on the Joplin's [website][joplin] that explains how to use [markdown][md].

[wiki]: https://evermeet.cx/wiki
[joplin]: https://joplinapp.org/
[md]: https://joplinapp.org/markdown/

The reference style links are maybe not that important for gh, but when you write your own markdown notes they are often useful.

P.S.: Thx, have a nice weekend as well.

**Comment by tessus** [comment]
I think we can close this....
