### ISSUE TITLE
Formatting Issue - Notebook Sidebar

### ISSUE THREAD

**Issue by SomeoneElseHasMyName** [tessus/joplin-plugin-menu-shortcut-toolbar#6]
The Notebook Sidebar shows the notebook list in one line, rather than an expanded view.  A scroll bar is shown [light purple in the image below].

![image](https://github.com/user-attachments/assets/d788d72a-01a0-4bfc-b615-32c298fdc692)

This occured since the last Joplin update - v3.0.13

Regressing back to the previous Joplin version clears the issue.

**Comment by tessus** [comment]
I am sorry. I fail to see what this has to do with this plugin. Can you please be a bit more sepecific what the issue is with this plugin?

**Comment by tessus** [comment]
Due to not getting any more info, I suspect this was a prank.
